function J=jac(u)
global gamma;

v = u(2) / u(1);
p = pEuler(u);
J = [ 0, ...
      1, ...
      0 ...
    ; 0.5 * (gamma-3) * v^2, ...
      (3-gamma) * v, ...
      gamma-1 ...
    ; 0.5 * (gamma-1) * v^3 - v * (u(3)+p) / u(1), ...
      (u(3)+p) / u(1) - (gamma-1) * v^2, ...
      gamma * v ...
    ];
