OCTAVE_VERSION = 3.0.0

LDADD +=  -lparseoctave -L$(top_srcdir)/syntax/libparseoctave \
 -lstratego-runtime ${SSL_LIBS} -loctave -loctinterp -lcruft \
 -L${OCTAVE}/lib/$(OCTAVE_SUBDIR) 
 
#AM_LDFLAGS += -rpath ${ATERM}/lib/aterm -rpath ${prefix}/lib/octavec -rpath ${OCTAVE}/lib/$(OCTAVE_SUBDIR)
AM_CPPFLAGS += -I$(top_srcdir)/syntax/libparseoctave

