[
   INT                      -- KW["Int"],
   FLOAT                    -- KW["Float"],
   STRING                   -- KW["String"],
   WORD                     -- KW["Word"],
   ADD                      -- KW["+"],
   SUB                      -- KW["-"],
   MULS                     -- KW["*s"],
   MULU                     -- KW["*"],
   MAC                      -- KW["mac"],
   DIVS                     -- KW["/s"],
   DIVU                     -- KW["/u"],
   NEG                      -- KW["-|"],
   AND                      -- KW["&"],
   OR                       -- KW["|"],
   XOR                      -- KW["xor"],
   NOT                      -- KW["not"],
   A                        -- KW["always"],
   N                        -- KW["never"],
   ASL                      -- KW["<a"],
   ASR                      -- KW[">a"],
   LSL                      -- KW["<l"],
   LSR                      -- KW[">l"],
   ROL                      -- KW["<r"],
   ROR                      -- KW[">r"],
   RCL                      -- KW["<c"],
   RCR                      -- KW[">c"],
   EQ                       -- KW["=i"],
   NE                       -- KW["~=i"],
   MI                       -- KW["min"],
   PL                       -- KW["plus"],
   VS                       -- KW["ows"],
   EQ                       -- KW["owc"],
   LO                       -- KW["lo"],
   LS                       -- KW["los"],
   HS                       -- KW["hs"],
   HI                       -- KW["hi"],
   LT                       -- KW["<s"],
   LE                       -- KW["<=s"],
   GE                       -- KW[">=s"],
   GT                       -- KW[">s"],
   PROGRAM                  -- V  [V vs=2 [KW["program"] _1] KW["end"]],
   PROGRAM.1:iter-star      -- _1,
   FUNCTION                 -- V is=2[ KW["function"] 
			         V is=2 [ KW["OUTLOC("] _1 ] KW[")"] 
			      _2 V is=2 [ KW["IN_LOC("] _3 ] KW[")"] ]
                                KW["end"],

   FUNCTION.1:iter-star-sep -- H[_1 KW[","]],
   FUNCTION.2:iter-star-sep -- H[_1 KW[";"]],
   FUNCTION.3:iter-star-sep -- H[_1 KW[","]],
   STRING                   -- KW["string"] _1 KW["="] _2,
   LOC                      -- H [KW["LOC("] _1 KW["::"] _2 KW[")"]],
   LABEL                    -- H[_1 KW[":"]],
   CONST                    -- H[ KW["CONST("]   _1 KW["<-"] _2  KW[")"]],
   LABELREF                 -- H[ KW["LABELREF"]  _1 KW["of"]  _2 ],
   DATA                     -- H[ _2 KW["<-"] _2 _1  _3 ],
   DATA.2:iter-star         -- _1,
   DATA.3:iter-star         -- _1,
   LOAD                     -- H[_1 KW["<- *"] _2],
   STORE                    -- H[KW["*"] _1 KW["<-"] _2],
   BRANCH                   -- H[KW["BRANCH"] _1 KW["("] _2 KW[")"] KW["iftrue"] _3 KW["iffalse"] _4],
   BRANCH.2:opt             -- _1,
   BRANCH.4:opt             -- _1,
   NOTE_LOC_BIRTH           -- H[KW["BIRTH"] _1],
   NOTE_LOC_DEATH           -- H[KW["DEATH"] _1],
   NOTE_LOOP_START          -- H[KW["LOOP:"] _1],
   NOTE_LOOP_FINISH         -- H[KW["LOOP END"] _1],
   IN_ARG                   -- H[KW["IN_ARG"] _1 _2],
   IN_RET                   -- H[KW["IN_RET"] _1 _2],
   OUT_ARG                  -- H[KW["OUT_ARG"] _1 _2],
   OUT_RET                  -- H[KW["OUT_RET"] _1 _2],
   ALLOC_FRAME              -- H[KW["ALLOC FRAME("] _1 KW["+"] _2 KW[")"] ],
   FREE_FRAME               -- H[KW["FREE FRAME("] _1 KW["+"] _2 KW[")"]],
   SEQS                     -- V  [ _1] ,
   SEQS.1:iter-sep          -- H[_1 KW[" "]],
   SEQ                      -- H[ _1 KW[";"] _2]
]
